# Generated by Django 2.2.6 on 2019-12-23 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191223_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='student_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='tc_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
