# Generated by Django 2.2.4 on 2019-12-25 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191223_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='tc_no',
            field=models.IntegerField(default=10000000000, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
