# Generated by Django 3.0.1 on 2019-12-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20190729_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': (('can_send', 'Can send message'),)},
        ),
    ]
