# Generated by Django 2.2.6 on 2019-12-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KisiselBilgiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('dtarihi', models.DateField()),
                ('dyeri', models.CharField(max_length=30)),
                ('mdurum', models.CharField(max_length=5)),
                ('ehliyet', models.BooleanField()),
                ('uyruk', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Kişisel Bilgiler',
            },
        ),
        migrations.CreateModel(
            name='YabanciDil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yAd', models.CharField(max_length=20)),
                ('ySeviye', models.CharField(max_length=10)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YabanciDil', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'Yabancı Dil Ve Seviyesi',
            },
        ),
        migrations.CreateModel(
            name='Referanslar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referans', models.CharField(blank=True, max_length=50)),
                ('referansverenkisiveyakurum', models.CharField(blank=True, max_length=30)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Referanslar', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'Referanslar',
            },
        ),
        migrations.CreateModel(
            name='KatildigiSeminerveKurslar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sTarihi', models.DateField(blank=True)),
                ('fTarihi', models.DateField(blank=True)),
                ('kurs', models.CharField(blank=True, max_length=50)),
                ('seminer', models.CharField(blank=True, max_length=50)),
                ('sertifikalar', models.CharField(blank=True, max_length=30)),
                ('sertifikano', models.CharField(blank=True, max_length=30)),
                ('dernekvekulupuyelikleri', models.CharField(blank=True, max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KatildigiSeminerveKurslar', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'KatildigiSeminerveKurslar',
            },
        ),
        migrations.CreateModel(
            name='IsDeneyimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sTarihi', models.DateField(blank=True)),
                ('fTarihi', models.DateField(blank=True)),
                ('sAD', models.TextField(blank=True)),
                ('unvan', models.CharField(max_length=30)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IsDeneyimi', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'İş Deneyimi',
            },
        ),
        migrations.CreateModel(
            name='IletisimBilgileri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eposta', models.EmailField(max_length=254)),
                ('tel1', models.CharField(max_length=30)),
                ('tel2', models.CharField(blank=True, max_length=30)),
                ('adres', models.TextField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IletisimBilgileri', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='EkBilgiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saglikdurumu', models.CharField(max_length=30)),
                ('askerlik', models.CharField(blank=True, max_length=15)),
                ('kariyerhedefi', models.TextField(max_length=60)),
                ('sigaraalkolkullanimi', models.CharField(blank=True, max_length=30)),
                ('eklIstedikleri', models.TextField(blank=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EkBilgiler', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'EkBilgiler',
            },
        ),
        migrations.CreateModel(
            name='EgitimBilgileri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sTarihi', models.DateField()),
                ('fTarihi', models.DateField()),
                ('oAd', models.TextField(max_length=50)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EgitimBilgileri', to='cv.KisiselBilgiler')),
            ],
            options={
                'verbose_name': 'Eğitim Bilgileri',
            },
        ),
    ]
