# Generated by Django 2.2.6 on 2019-12-23 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='dtarihi',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='dyeri',
        ),
        migrations.RemoveField(
            model_name='kisiselbilgiler',
            name='soyad',
        ),
        migrations.AlterField(
            model_name='kisiselbilgiler',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
