# Generated by Django 2.2.6 on 2019-12-23 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20191223_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egitimbilgileri',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EgitimBilgileri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ekbilgiler',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EkBilgiler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iletisimbilgileri',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IletisimBilgileri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='isdeneyimi',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IsDeneyimi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='katildigiseminervekurslar',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KatildigiSeminerveKurslar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referanslar',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Referanslar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yabancidil',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YabanciDil', to=settings.AUTH_USER_MODEL),
        ),
    ]
